In [ ]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [55]:
# Data cleansing
StudentFile = pd.read_csv('D:\\College\\Senior-2 CSE 2\\Big Data\\uci-open-university-learning-analytics-dataset\\studentInfo.csv')
StudentAssesmentFile = pd.read_csv('D:\\College\\Senior-2 CSE 2\\Big Data\\uci-open-university-learning-analytics-dataset\\studentAssessment.csv')

mergedFile = pd.merge(StudentFile,StudentAssesmentFile,on='id_student',how='inner')
mergedFile.drop('is_banked',axis=1,inplace=True)

mergedFile.drop('date_submitted',axis=1,inplace=True)


mergedFile.replace({'score':'?'}, pd.NA, inplace=True)  # Replace '?' with NaN


mergedFile.replace({'imd_band':'?'}, pd.NA, inplace=True)  # Replace '?' with NaN

mergedFile = mergedFile.dropna(subset=['score', 'imd_band'])

mergedFile['imd_band'] = mergedFile['imd_band'].replace('20-oct-2024', '10-20%')

# One-hot encoding for the features:
mergedFile.drop('code_module',axis=1,inplace=True)
mergedFile.drop('code_presentation',axis=1,inplace=True)
mergedFile.drop('highest_education',axis=1,inplace=True)

mergedFile= mergedFile[mergedFile['final_result'] != 'withdrawn'or'Distinction']

mergedFile['final_result'] = mergedFile['final_result'].replace({'Pass': 1, 'Fail': 0})


encoded_data= pd.get_dummies(mergedFile,columns=['gender','id_assessment','region','disability','age_band']).astype(int)


ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [13]:
# File after Cleansing
data = pd.read_csv('D:\\College\\Senior-2 CSE 2\\Big Data\\uci-open-university-learning-analytics-dataset\\merged2001.csv')


In [14]:
# data.replace('?', pd.NA, inplace=True)  # Replace '?' with NaN
# data.dropna(inplace=True)  # Drop rows containing NaN
# data = pd.get_dummies(data, columns=['gender', 'disability'])

In [15]:
## X = data[['gender_F','gender_M','highest_education_A Level or Equivalent','highest_education_HE Qualification','highest_education_Lower Than A Level','highest_education_No Formal quals','highest_education_Post Graduate Qualification','disability_N','disability_Y','age_band_0-35','age_band_35-55','age_band_55<=','studied_credits','num_of_prev_attempts','code_module_AAA','code_module_BBB','code_module_CCC','code_module_DDD','code_module_EEE','code_module_FFF','code_module_GGG','code_presentation_2013B'	,'code_presentation_2013J'	,'code_presentation_2014B'	,'code_presentation_2014J']].values
y = data[['final_result']].values
column_indexes = list(range(15, 208))
X = data.iloc[:,column_indexes].values

# 'gender_F','gender_M','disability_Y','disability_N','age_band ID','studied_credits','0','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31','32','34','35','36','37','38','39','40','41','42','43','44','45','46','47','48','49','50','51','52','53','54','55','56','57','58','59','60','61','62','63','64','65','66','67','68','69','70','71','72','73','74','75','76','77','78','79','80','81','82','83','84','85','86','87','88','89','90','91','92','93','94','95','96','97','98','99','100','101','102','103','104','105','106','107','108','109','110','111','112','113','114','115','116','117','118','119','120','121','122','123','124','125','126','127','128','129','130','131','132','133','134',,'135','136','137','138','139','140','141','142','143','144','145','146','147','148','149','150','151','152','153','154','155','156','157','158','159','160','161','162','163','164','165','166','167','168','169','170','171','172','173','174','175','176','177','178','179','180','181','182','183','184','185','186','187'

In [16]:
X

array([[1, 0, 0, ..., True, True, False],
       [0, 1, 0, ..., True, True, False],
       [0, 0, 1, ..., True, True, False],
       ...,
       [0, 0, 0, ..., False, False, True],
       [0, 0, 0, ..., False, False, True],
       [0, 0, 0, ..., False, False, True]], dtype=object)

In [17]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(X, y, test_size= 0.25, random_state=0)

In [18]:
from sklearn.neighbors import KNeighborsClassifier  
classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)  
classifier.fit(x_train, y_train)

C:\Users\musta\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [19]:
y_pred = classifier.predict(x_test)  

In [20]:
y_test

array([['Pass'],
       ['Pass'],
       ['Pass'],
       ...,
       ['Pass'],
       ['Fail'],
       ['Pass']], dtype=object)

In [21]:
y_pred

array(['Fail', 'Pass', 'Pass', ..., 'Pass', 'Pass', 'Pass'], dtype=object)

In [22]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm = confusion_matrix(y_test, y_pred)  
cm

array([[  902,  7316],
       [ 2062, 27440]], dtype=int64)

In [23]:
from sklearn.metrics import accuracy_score  
accuracy_score(y_test, y_pred)

0.7513785790031814

In [24]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [25]:
from sklearn.preprocessing import StandardScaler  
sc = StandardScaler()  
x_train = sc.fit_transform(x_train)  
x_test = sc.transform(x_test)

In [26]:
# Fitting Naive Bayes to the Training set  
from sklearn.naive_bayes import GaussianNB  
classifier = GaussianNB()  
classifier.fit(x_train, y_train)  

C:\Users\musta\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [27]:
# Predicting the Test set results  
y_pred = classifier.predict(x_test) 

In [28]:
# Making the Confusion Matrix  
from sklearn.metrics import confusion_matrix  
cm = confusion_matrix(y_test, y_pred) 
cm

array([[ 5586,  2632],
       [14650, 14852]], dtype=int64)

In [29]:
from sklearn.metrics import accuracy_score  
accuracy_score(y_test, y_pred)

0.5418345705196183

In [30]:
# Splitting the dataset into training and test set. 
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [31]:
#feature Scaling
from sklearn.preprocessing import StandardScaler    
st_x = StandardScaler()  
#fit the training data to calculate the mean and std, then transform the tarining data
x_train = st_x.fit_transform(x_train)    
#transform the testing data using the same fit result of training data
x_test = st_x.transform(x_test)

In [32]:
#Fitting Decision Tree classifier to the training set  
from sklearn.tree import DecisionTreeClassifier  
classifier= DecisionTreeClassifier(criterion='entropy', random_state=0)  
classifier.fit(x_train, y_train)  

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [33]:
#Predicting the test set result  
y_pred = classifier.predict(x_test)
y_pred, y_test

(array(['Pass', 'Pass', 'Pass', ..., 'Pass', 'Pass', 'Pass'], dtype=object),
 array([['Pass'],
        ['Pass'],
        ['Pass'],
        ...,
        ['Pass'],
        ['Fail'],
        ['Pass']], dtype=object))

In [35]:
y_pred

array(['Pass', 'Pass', 'Pass', ..., 'Pass', 'Pass', 'Pass'], dtype=object)

In [36]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)
cm

array([[   36,  8182],
       [   75, 29427]], dtype=int64)

In [37]:
from sklearn.metrics import accuracy_score  
accuracy_score(y_test, y_pred)

0.7810975609756098

In [38]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [39]:
df = pd.read_csv('D:\\College\\Senior-2 CSE 2\\Big Data\\uci-open-university-learning-analytics-dataset\\merged2001.csv')
df['final_result'] = df['final_result'].replace({'Pass': 1, 'Fail': 0})
df['gender_F'] = df['gender_F'].astype(int)
df['gender_M'] = df['gender_M'].astype(int)
df['disability_Y'] = df['disability_Y'].astype(int)
df['disability_N'] = df['disability_N'].astype(int)

C:\Users\musta\AppData\Local\Temp\ipykernel_24064\3172843438.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['final_result'] = df['final_result'].replace({'Pass': 1, 'Fail': 0})


In [40]:
# X = pd.get_dummies(df.drop(['Churn', 'Customer ID'], axis=1))
# y = df['Churn'].apply(lambda x: 1 if x=='Yes' else 0
y = df['final_result'].apply(lambda x: 1 if x=='Pass' else 0)
# y = df[['final_result']].values
column_indexes = list(range(14, 208))
X = df.iloc[:,column_indexes]


In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)

In [42]:
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense
from sklearn.metrics import accuracy_score

In [43]:
model = Sequential()
model.add(Dense(units=64, activation='relu', input_dim=len(X_train.columns)))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=1, activation='sigmoid'))
model

C:\Users\musta\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\keras\src\layers\core\dense.py:85: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


<Sequential name=sequential_1, built=True>

In [44]:
import tensorflow as tf
model.compile(loss='binary_crossentropy', optimizer=tf.keras.optimizers.Adam(0.001))


In [45]:
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
3772/3772 ━━━━━━━━━━━━━━━━━━━━ 5s 960us/step - loss: 0.0237
Epoch 2/10
3772/3772 ━━━━━━━━━━━━━━━━━━━━ 4s 967us/step - loss: 1.6937e-07
Epoch 3/10
3772/3772 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 1.7325e-08
Epoch 4/10
3772/3772 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 2.5686e-09
Epoch 5/10
3772/3772 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 5.5152e-10
Epoch 6/10
3772/3772 ━━━━━━━━━━━━━━━━━━━━ 4s 998us/step - loss: 1.7488e-10
Epoch 7/10
3772/3772 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 7.3381e-11
Epoch 8/10
3772/3772 ━━━━━━━━━━━━━━━━━━━━ 4s 935us/step - loss: 3.8899e-11
Epoch 9/10
3772/3772 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 2.5124e-11
Epoch 10/10
3772/3772 ━━━━━━━━━━━━━━━━━━━━ 4s 990us/step - loss: 1.8268e-11


In [46]:
y_hat = model.predict(X_test)
y_hat = [0 if val < 0.5 else 1 for val in y_hat]

943/943 ━━━━━━━━━━━━━━━━━━━━ 1s 853us/step


In [47]:
# check wrong predictions
j = 0
for i in range(len(y_hat)):
    if y_hat[i] != y_test.iloc[i]:
        j = j=1

print(f'the number of wrong predictions is: {j}')

the number of wrong predictions is: 0


In [48]:
accuracy_score(y_test, y_hat)

1.0

In [50]:
data = pd.read_csv('D:\\College\\Senior-2 CSE 2\\Big Data\\uci-open-university-learning-analytics-dataset\\merged2001.csv')

In [51]:
y = data[['final_result']].values
column_indexes = list(range(14, 208))
X = data.iloc[:,column_indexes].values


In [52]:
# Splitting the dataset into the Training set and Test set  
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [53]:
# Feature Scaling  
from sklearn.preprocessing import StandardScaler  
sc = StandardScaler()  
x_train = sc.fit_transform(x_train)  
x_test = sc.transform(x_test)

In [54]:
# Fitting the Training set  using Support vector classifier
from sklearn.svm import SVC
classifier = SVC(kernel='linear')
#classifier = SVC(kernel='poly')
#classifier = SVC(kernel='rbf')
#classifier = SVC(kernel='sigmoid')
classifier.fit(x_train, y_train)  

C:\Users\musta\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear')

In [ ]:
# Predicting the Test set results  
y_pred = classifier.predict(x_test) 

In [ ]:
# Making the Confusion Matrix  
from sklearn.metrics import confusion_matrix  
cm = confusion_matrix(y_test, y_pred) 
cm

In [ ]:
from sklearn.metrics import accuracy_score  
accuracy_score(y_test, y_pred)

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel='sigmoid')
classifier.fit(x_train, y_train)  

In [ ]:
# Predicting the Test set results  
y_pred = classifier.predict(x_test) 

In [ ]:
# Making the Confusion Matrix  
from sklearn.metrics import confusion_matrix  
cm = confusion_matrix(y_test, y_pred) 
cm

In [ ]:
from sklearn.metrics import accuracy_score  
accuracy_score(y_test, y_pred)

In [ ]:
data = pd.read_csv('D:\\College\\Senior-2 CSE 2\\Big Data\\uci-open-university-learning-analytics-dataset\\merged2001.csv')

In [ ]:
y_soft = data['new score']
column_indexes = list(range(14, 208))
X_soft = data.iloc[:,column_indexes].astype(int)

In [ ]:
import tensorflow as tf
y_train_onehot = tf.keras.utils.to_categorical(y_soft, num_classes=10)

In [ ]:
# Splitting the dataset into the Training set and Test set  
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X_soft, y_train_onehot, test_size = 0.25, random_state = 0)

In [ ]:
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense
from sklearn.metrics import accuracy_score
softmax_model = Sequential()
softmax_model.add(Dense(units=512, activation='relu', input_dim=len(X_train.columns)))
softmax_model.add(Dense(units=1024, activation='relu'))
softmax_model.add(Dense(units=512, activation='relu'))
softmax_model.add(Dense(units=10, activation='softmax'))


In [ ]:
softmax_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:

softmax_model.fit(X_train, y_train_onehot, epochs=10, batch_size=32, validation_split=0.2)

In [ ]:
loss, accuracy = softmax_model.evaluate(X_train, y_train)
print("Accuracy:", accuracy)