In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [2]:
data = pd.read_csv('D:\\College\\Senior-2 CSE 2\\Big Data\\uci-open-university-learning-analytics-dataset\\test2.csv')

In [50]:
# data.replace('?', pd.NA, inplace=True)  # Replace '?' with NaN
# data.dropna(inplace=True)  # Drop rows containing NaN
# data = pd.get_dummies(data, columns=['gender', 'disability'])

In [52]:
data.to_csv('D:\\College\\Senior-2 CSE 2\\Big Data\\uci-open-university-learning-analytics-dataset\\merged32.csv')

In [54]:
data = pd.read_csv('D:\\College\\Senior-2 CSE 2\\Big Data\\uci-open-university-learning-analytics-dataset\\merged32.csv')

In [6]:
data.iloc[:,218]

0         7
1         8
2         8
3         8
4         8
         ..
150874    6
150875    8
150876    9
150877    9
150878    8
Name: new score, Length: 150879, dtype: int64

In [7]:
## X = data[['gender_F','gender_M','highest_education_A Level or Equivalent','highest_education_HE Qualification','highest_education_Lower Than A Level','highest_education_No Formal quals','highest_education_Post Graduate Qualification','disability_N','disability_Y','age_band_0-35','age_band_35-55','age_band_55<=','studied_credits','num_of_prev_attempts','code_module_AAA','code_module_BBB','code_module_CCC','code_module_DDD','code_module_EEE','code_module_FFF','code_module_GGG','code_presentation_2013B'	,'code_presentation_2013J'	,'code_presentation_2014B'	,'code_presentation_2014J']].values
y = data[['new score']].values
column_indexes = list(range(13, 218))
X = data.iloc[:,column_indexes]

# 'gender_F','gender_M','disability_Y','disability_N','age_band ID','studied_credits','0','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31','32','34','35','36','37','38','39','40','41','42','43','44','45','46','47','48','49','50','51','52','53','54','55','56','57','58','59','60','61','62','63','64','65','66','67','68','69','70','71','72','73','74','75','76','77','78','79','80','81','82','83','84','85','86','87','88','89','90','91','92','93','94','95','96','97','98','99','100','101','102','103','104','105','106','107','108','109','110','111','112','113','114','115','116','117','118','119','120','121','122','123','124','125','126','127','128','129','130','131','132','133','134',,'135','136','137','138','139','140','141','142','143','144','145','146','147','148','149','150','151','152','153','154','155','156','157','158','159','160','161','162','163','164','165','166','167','168','169','170','171','172','173','174','175','176','177','178','179','180','181','182','183','184','185','186','187'

In [8]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(X, y, test_size= 0.25, random_state=0)

In [70]:
from sklearn.neighbors import KNeighborsClassifier  
classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )  
classifier.fit(x_train, y_train) 

C:\Users\musta\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [71]:
y_pred = classifier.predict(x_test) 

In [72]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm = confusion_matrix(y_test, y_pred)  
cm

array([[  881,  7337],
       [ 1975, 27527]], dtype=int64)

In [73]:
from sklearn.metrics import accuracy_score  
accuracy_score(y_test, y_pred)

0.7531283138918345

In [74]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [75]:
from sklearn.preprocessing import StandardScaler  
sc = StandardScaler()  
x_train = sc.fit_transform(x_train)  
x_test = sc.transform(x_test)

In [76]:
# Fitting Naive Bayes to the Training set  
from sklearn.naive_bayes import GaussianNB  
classifier = GaussianNB()  
classifier.fit(x_train, y_train)  

C:\Users\musta\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [77]:
# Predicting the Test set results  
y_pred = classifier.predict(x_test) 

In [78]:
# Making the Confusion Matrix  
from sklearn.metrics import confusion_matrix  
cm = confusion_matrix(y_test, y_pred) 
cm

array([[ 5586,  2632],
       [14650, 14852]], dtype=int64)

In [79]:
from sklearn.metrics import accuracy_score  
accuracy_score(y_test, y_pred)

0.5418345705196183

In [9]:
# Splitting the dataset into training and test set. 
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [18]:
#feature Scaling
from sklearn.preprocessing import StandardScaler    
st_x = StandardScaler()  
#fit the training data to calculate the mean and std, then transform the tarining data
x_train = st_x.fit_transform(x_train)    
#transform the testing data using the same fit result of training data
x_test = st_x.transform(x_test)

In [19]:
#Fitting Decision Tree classifier to the training set  
from sklearn.tree import DecisionTreeClassifier  
classifier= DecisionTreeClassifier(criterion='entropy', random_state=0)  
classifier.fit(x_train, y_train)  

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [20]:
#Predicting the test set result  
y_pred = classifier.predict(x_test)
y_pred, y_test

(array([5, 9, 5, ..., 9, 8, 9], dtype=int64),
 array([[7],
        [9],
        [6],
        ...,
        [9],
        [6],
        [9]], dtype=int64))

In [21]:
y_test

array([[7],
       [9],
       [6],
       ...,
       [9],
       [6],
       [9]], dtype=int64)

In [22]:
y_pred

array([5, 9, 5, ..., 9, 8, 9], dtype=int64)

In [23]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)
cm

array([[  37,    0,    0,    0,    3,    4,   20,   31,   27,  122],
       [   1,    1,    6,    2,    7,   12,   25,   41,   40,   56],
       [   1,    2,    7,    8,   14,   43,   57,   86,   97,  135],
       [   0,    1,   11,   24,   35,   65,  111,  190,  132,  177],
       [   3,    2,    6,   19,   73,  118,  304,  424,  330,  493],
       [   6,    7,   11,   28,   65,  236,  461,  884,  522,  588],
       [   6,    7,   11,   32,  121,  273,  991, 1716, 1140, 1328],
       [   3,    6,   21,   31,  106,  293,  987, 2607, 1724, 1358],
       [   3,   11,   23,   25,  109,  238,  747, 2164, 2455, 3033],
       [  33,   10,   19,   31,  108,  202,  608, 1556, 2089, 5284]],
      dtype=int64)

In [24]:
from sklearn.metrics import accuracy_score  
accuracy_score(y_test, y_pred)

0.3105779427359491